apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frps-webhook-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
