# This rule is not used by the project cloud-nexus-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to tunnel.tunnel.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloud-nexus-operator
    app.kubernetes.io/managed-by: kustomize
  name: frpproxy-viewer-role
rules:
- apiGroups:
  - tunnel.tunnel.io
  resources:
  - frpproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tunnel.tunnel.io
  resources:
  - frpproxies/status
  verbs:
  - get
