---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunnel.tunnel.io
  resources:
  - frpclients
  - frpservers
  - httpproxies
  - httpsproxies
  - registryproxies
  - stcpproxies
  - sudpproxies
  - tcpmuxproxies
  - tcpproxies
  - udpproxies
  - xtcpproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tunnel.tunnel.io
  resources:
  - frpclients/finalizers
  - frpservers/finalizers
  - httpproxies/finalizers
  - httpsproxies/finalizers
  - registryproxies/finalizers
  - stcpproxies/finalizers
  - sudpproxies/finalizers
  - tcpmuxproxies/finalizers
  - tcpproxies/finalizers
  - udpproxies/finalizers
  - xtcpproxies/finalizers
  verbs:
  - update
- apiGroups:
  - tunnel.tunnel.io
  resources:
  - frpclients/status
  - frpservers/status
  - httpproxies/status
  - httpsproxies/status
  - registryproxies/status
  - stcpproxies/status
  - sudpproxies/status
  - tcpmuxproxies/status
  - tcpproxies/status
  - udpproxies/status
  - xtcpproxies/status
  verbs:
  - get
  - patch
  - update
